#ifndef DOSIMETER_SBM19_NEXT_CONFIG_H_INCLUDED
#define DOSIMETER_SBM19_NEXT_CONFIG_H_INCLUDED

	#define SOFT_VERSION			100
	#define	START_RADIATION_VALUE	95
	#define	VALUE_ARRAY_CNT			100

#endif	//	DOSIMETER_SBM19_NEXT_CONFIG_H_INCLUDED
